In [ ]:
#Validaciones para hacer fantasmas

In [3]:
import pandas as pd

In [ ]:


archivo=pd.read_parquet(r"C:\Users\katherine.Builes\OneDrive - Valor+ SAS\utilidades\omisos\data omisos\output\omisos_calculos.parquet")

In [12]:
fantasma = pd.read_excel(r"C:\Users\katherine.Builes\OneDrive - Valor+ SAS\utilidades\omisos\fantasmas_qloudsi.xlsx", sheet_name='datos')

In [13]:
fantasma_qa=pd.read_csv(r"C:\Users\katherine.Builes\OneDrive - Valor+ SAS\utilidades\omisos\fantasma_qa.csv", sep=";")

In [14]:
cond_fantasma = fantasma_qa['Placa'].isin(fantasma['noPlaca'])
fantasma_qa.loc[cond_fantasma, 'FANTASMA_IF'] = 'SI'

In [15]:
fantasma_final = fantasma_qa[(fantasma_qa['Estado_2']=='fantasma')&(fantasma_qa['FANTASMA_IF']=='SI')]['Placa']

In [19]:
fantasma_final

6186       A1629
6188      AAA119
6191      AAA285
6192      AAA318
6199      AAA465
           ...
448356     YBQ20
448431     ZPB19
448433     ZPJ15
448443     ZXV42
448444     ZXY12
Name: Placa, Length: 51540, dtype: object

In [20]:
fantasmas_validacion=pd.DataFrame(fantasma_final)

In [22]:
fantasmas_validacion.shape

(51540, 1)

In [25]:
fantasmas_validacion=fantasmas_validacion.drop_duplicates()

In [26]:
fantasmas_validacion.shape

(51540, 1)

In [27]:
valores=pd.read_parquet(r"C:\Users\katherine.Builes\OneDrive - Valor+ SAS\utilidades\omisos\data omisos\output\parque_total_20250507_valores.parquet")

In [28]:
valores['IMPUESTO_CALCULADO'] = (valores['IMPUESTO_CALCULADO']/1000).round()*1000
valores['SANCION_CALCULADA'] = (valores['SANCION_CALCULADA']/1000).round()*1000
valores['INTERESES_CALCULADOS'] = (valores['INTERESES_CALCULADOS']/1000).round()*1000

In [29]:
cond_fantasma = valores['PLACA'].isin(fantasma_final)
valores.loc[cond_fantasma, 'ESTADO'] = 'FANTASMA'

In [30]:
valores[valores["PLACA"]=="AAA119"]

,PLACA,ESTADO,MUNICIPIO,DEPARTAMENTO,INTERLOCUTOR_COMERCIAL,ID_USUARIO,TIPO_DOCUMENTO,VIGENCIA,SUBREGION,CLASE,FECHA_MATRICULA,IMPUESTO,SANCIONES,INTERESES,IMPUESTO_CALCULADO,SANCION_CALCULADA,INTERESES_CALCULADOS
189313,AAA119,FANTASMA,MEDELLIN,ANTIOQUIA,None,8250466,1,2004,VALLE DEL ABURRA,VEHICULOS,1976-11-04,37000.0,141000.0,107000.0,37000.0,249000.0,201000.0
557225,AAA119,FANTASMA,MEDELLIN,ANTIOQUIA,None,8250466,1,2005,VALLE DEL ABURRA,VEHICULOS,1976-11-04,31000.0,141000.0,82000.0,31000.0,249000.0,161000.0
958663,AAA119,FANTASMA,MEDELLIN,ANTIOQUIA,None,8250466,1,2006,VALLE DEL ABURRA,VEHICULOS,1976-11-04,33000.0,141000.0,79000.0,33000.0,249000.0,164000.0
1399701,AAA119,FANTASMA,MEDELLIN,ANTIOQUIA,None,8250466,1,2007,VALLE DEL ABURRA,VEHICULOS,1976-11-04,34000.0,141000.0,73000.0,34000.0,249000.0,163000.0
1885704,AAA119,FANTASMA,MEDELLIN,ANTIOQUIA,None,8250466,1,2008,VALLE DEL ABURRA,VEHICULOS,1976-11-04,32000.0,141000.0,60000.0,32000.0,249000.0,143000.0
2411322,AAA119,FANTASMA,MEDELLIN,ANTIOQUIA,None,8250466,1,2009,VALLE DEL ABURRA,VEHICULOS,1976-11-04,30000.0,141000.0,48000.0,30000.0,249000.0,125000.0
2986311,AAA119,FANTASMA,MEDELLIN,ANTIOQUIA,None,8250466,1,2010,VALLE DEL ABURRA,VEHICULOS,1976-11-04,32000.0,141000.0,44000.0,32000.0,249000.0,124000.0
3624994,AAA119,FANTASMA,MEDELLIN,ANTIOQUIA,None,8250466,1,2011,VALLE DEL ABURRA,VEHICULOS,1976-11-04,33000.0,141000.0,38000.0,33000.0,249000.0,123000.0
4322943,AAA119,FANTASMA,MEDELLIN,ANTIOQUIA,None,8250466,1,2012,VALLE DEL ABURRA,VEHICULOS,1976-11-04,35000.0,141000.0,31000.0,34000.0,249000.0,120000.0
5082216,AAA119,FANTASMA,MEDELLIN,ANTIOQUIA,None,8250466,1,2013,VALLE DEL ABURRA,VEHICULOS,1976-11-04,30000.0,141000.0,19000.0,30000.0,249000.0,96000.0
5910875,AAA119,FANTASMA,MEDELLIN,ANTIOQUIA,None,8250466,1,2014,VALLE DEL ABURRA,VEHICULOS,1976-11-04,29000.0,166000.0,10000.0,28000.0,249000.0,83000.0
6789142,AAA119,FANTASMA,MEDELLIN,ANTIOQUIA,None,8250466,1,2015,VALLE DEL ABURRA,VEHICULOS,1976-11-04,27000.0,166000.0,3000.0,27000.0,249000.0,72000.0
7739064,AAA119,FANTASMA,MEDELLIN,ANTIOQUIA,None,8250466,1,2016,VALLE DEL ABURRA,VEHICULOS,1976-11-04,20000.0,171000.0,0.0,20000.0,249000.0,47000.0
8757449,AAA119,FANTASMA,MEDELLIN,ANTIOQUIA,None,8250466,1,2017,VALLE DEL ABURRA,VEHICULOS,1976-11-04,71000.0,178000.0,0.0,70000.0,249000.0,151000.0
9846198,AAA119,FANTASMA,MEDELLIN,ANTIOQUIA,None,8250466,1,2018,VALLE DEL ABURRA,VEHICULOS,1976-11-04,80000.0,190000.0,35000.0,80000.0,249000.0,150000.0
11014879,AAA119,FANTASMA,MEDELLIN,ANTIOQUIA,None,8250466,1,2019,VALLE DEL ABURRA,VEHICULOS,1976-11-04,18000.0,212000.0,8000.0,18000.0,249000.0,30000.0
12256451,AAA119,FANTASMA,MEDELLIN,ANTIOQUIA,None,8250466,1,2020,VALLE DEL ABURRA,VEHICULOS,1976-11-04,18000.0,249000.0,0.0,18000.0,249000.0,25000.0
13603382,AAA119,FANTASMA,MEDELLIN,ANTIOQUIA,None,8250466,1,2021,VALLE DEL ABURRA,VEHICULOS,1976-11-04,17000.0,249000.0,0.0,17000.0,249000.0,20000.0
15063758,AAA119,FANTASMA,MEDELLIN,ANTIOQUIA,None,8250466,1,2022,VALLE DEL ABURRA,VEHICULOS,1976-11-04,17000.0,249000.0,0.0,17000.0,249000.0,16000.0
16616235,AAA119,FANTASMA,MEDELLIN,ANTIOQUIA,None,8250466,1,2023,VALLE DEL ABURRA,VEHICULOS,1976-11-04,17000.0,249000.0,0.0,17000.0,249000.0,9000.0
18277037,AAA119,FANTASMA,MEDELLIN,ANTIOQUIA,None,8250466,1,2024,VALLE DEL ABURRA,VEHICULOS,1976-11-04,17000.0,0.0,0.0,17000.0,249000.0,3000.0
19935079,AAA119,FANTASMA,MEDELLIN,ANTIOQUIA,None,8250466,1,2025,VALLE DEL ABURRA,VEHICULOS,1976-11-04,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
valores.shape

(20346921, 17)

In [33]:
valores.to_parquet(r"C:\Users\katherine.Builes\OneDrive - Valor+ SAS\utilidades\omisos\data omisos\output\parque_total_20250507_valores_fantasmas.parquet")

In [7]:
archivo.sample(5)

,PLACA,ESTADO,MUNICIPIO,DEPARTAMENTO,INTERLOCUTOR_COMERCIAL,ID_USUARIO_x,TIPO_DOCUMENTO,VIGENCIA,SUBREGION,NIV_RECLAMACION,...,SISTEMATIZACION,NUMERO DE MESES,FECHA VENCIMIENTO,TARIFA,NOMBRE RANGO,FECHA,IMPUESTO_CALCULADO,SANCION_CALCULADA,AÑO MATRICULA,INTERESES_CALCULADOS
3197906,SSN02E,PLACA OMISA,ITAGUI,ANTIOQUIA,None,1041267335,C,2024.0,VALLE DEL ABURRA,00,...,23400.0,8,2024-07-19,1.5,[0 - 5.000.000],2025-05-03,61200.0,249000.0,2018.0,10869
2754965,LDA597,PLACA OMISA,ARMENIA,QUINDIO,None,7533624,1,2022.0,SIN SUBREGION,08,...,21450.0,32,2022-07-18,1.5,[0 - 5.000.000],2025-05-03,21150.0,249000.0,1974.0,19348
71519,FID30,PLACA OMISA,SEGOVIA,ANTIOQUIA,None,71082201,C,2005.0,NORDESTE,13,...,14000.0,237,2005-06-17,1.5,[0 - 5.000.000],2025-05-03,42000.0,249000.0,1996.0,216868
1098767,IRD29B,PLACA OMISA,MEDELLIN,ANTIOQUIA,1000914808,98611964,CC,2015.0,VALLE DEL ABURRA,13,...,15000.0,116,2015-07-17,1.5,[0 - 5.000.000],2025-05-03,66000.0,249000.0,2008.0,175233
1340518,TAC568,PLACA OMISA,ENVIGADO,ANTIOQUIA,None,3660041,C,2017.0,VALLE DEL ABURRA,00,...,17100.0,92,2017-07-14,1.5,[0 - 5.000.000],2025-05-03,22050.0,249000.0,1961.0,46646

In [6]:
archivo["AVALUO"].dtypes

dtype('float64')

In [19]:
info=pd.read_excel(r"C:\Users\katherine.Builes\OneDrive - Valor+ SAS\utilidades\omisos\vero_info.xlsx", header=1,dtype=str)

In [22]:
info["VIGENCIA"] = info["VIGENCIA"].astype("string")
meses = info[['VIGENCIA', 'NUMERO DE MESES', 'FECHA VENCIMIENTO']].dropna(subset=['VIGENCIA'])
tarifa = info[['AÑO', 'NOMBRE RANGO', 'INICIO', 'FIN', 'TARIFA']]

In [23]:
meses = meses[meses['VIGENCIA'].notna()]

In [24]:
info.head()

,VIGENCIA,NUMERO DE MESES,FECHA VENCIMIENTO,AÑO ACTUAL,MES ACTUAL,MES VENCIMIENTO,Unnamed: 6,AÑO,NOMBRE RANGO,INICIO,FIN,TARIFA
0,2004,249,2004-06-16 00:00:00,2025,2,7,NaN,2004,[0 - 5.000.000],0,5000000,1.5
1,2005,237,2005-06-17 00:00:00,2025,2,7,NaN,2004,[5.000.001 - 10.000.000],5000001,10000000,1.5
2,2006,225,2006-06-30 00:00:00,2025,2,7,NaN,2004,[10.000.001 - 20.000.000],10000001,20000000,1.5
3,2007,213,2007-06-29 00:00:00,2025,2,7,NaN,2004,[20.000.001 - 27.844.000],20000001,27844000,1.5
4,2008,200,2008-07-01 00:00:00,2025,2,6,NaN,2004,[27.844.001 - 62.648.000],27844001,62648000,2.5

In [25]:
archivo.columns

Index(['PLACA', 'ESTADO', 'MUNICIPIO', 'DEPARTAMENTO',
       'INTERLOCUTOR_COMERCIAL', 'ID_USUARIO_x', 'TIPO_DOCUMENTO', 'VIGENCIA',
       'SUBREGION', 'NIV_RECLAMACION', 'AVALUO', 'IMPUESTO', 'SANCIONES',
       'INTERESES', 'SISTEMATIZACION', 'NUMERO DE MESES', 'FECHA VENCIMIENTO',
       'TARIFA', 'NOMBRE RANGO'],
      dtype='object')

In [26]:
archivo["TARIFA"].value_counts()

TARIFA
1.5    3690663
2.5      47419
3.5       9858
Name: count, dtype: int64

In [27]:
print("Tipos de tarifa['AÑO']:", tarifa['AÑO'].dtype)
print("Tipos de omisos_calculos['VIGENCIA']:", archivo['VIGENCIA'].dtype)

Tipos de tarifa['AÑO']: object
Tipos de omisos_calculos['VIGENCIA']: object

In [28]:
tarifa['AÑO'] = tarifa['AÑO'].astype("string")

C:\Users\katherine.Builes\AppData\Local\Temp\ipykernel_19548\2712986773.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tarifa['AÑO'] = tarifa['AÑO'].astype("string")

In [29]:
meses.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22 entries, 0 to 21
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   VIGENCIA           22 non-null     string
 1   NUMERO DE MESES    22 non-null     object
 2   FECHA VENCIMIENTO  22 non-null     object
dtypes: object(2), string(1)
memory usage: 704.0+ bytes

In [30]:
archivo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3747940 entries, 0 to 3747939
Data columns (total 19 columns):
 #   Column                  Dtype
---  ------                  -----
 0   PLACA                   object
 1   ESTADO                  object
 2   MUNICIPIO               object
 3   DEPARTAMENTO            object
 4   INTERLOCUTOR_COMERCIAL  object
 5   ID_USUARIO_x            object
 6   TIPO_DOCUMENTO          object
 7   VIGENCIA                object
 8   SUBREGION               object
 9   NIV_RECLAMACION         category
 10  AVALUO                  float64
 11  IMPUESTO                float64
 12  SANCIONES               float64
 13  INTERESES               float64
 14  SISTEMATIZACION         float64
 15  NUMERO DE MESES         float64
 16  FECHA VENCIMIENTO       datetime64[ns]
 17  TARIFA                  float64
 18  NOMBRE RANGO            object
dtypes: category(1), datetime64[ns](1), float64(7), object(10)
memory usage: 518.3+ MB

In [31]:
vigencias_info = set(info['VIGENCIA'].unique())
vigencias_omisos = set(archivo['VIGENCIA'].unique())
print("Coincidencias:", vigencias_info & vigencias_omisos)
print("No están en omisos:", vigencias_info - vigencias_omisos)

Coincidencias: {'2025', '2020', '2021', '2023', '2010', '2022', '2008', '2018', '2019', '2014', '2017', '2007', '2009', '2015', '2024', '2006', '2005', '2016', '2012', '2013', '2011', '2004'}
No están en omisos: {<NA>}

In [1]:
import os
from datetime import datetime
from pathlib import Path
import pandas as pd

In [2]:

home = str(Path.home())

In [3]:
base_dir = os.path.join(home, "OneDrive - Valor+ SAS")


utilidades_dir = os.path.join(base_dir, "utilidades", "reportes")

In [4]:
analitica_dir = os.path.join(base_dir, "analitica_impuestos", "depurada")

In [5]:
output_dir = os.path.join(utilidades_dir, "output")

In [6]:
pagos_file = os.path.join(output_dir, "consolidado_pagos.parquet")
pagos_dm_file = os.path.join(analitica_dir, "pagos.parquet")

In [7]:
pagos = pd.read_parquet(pagos_file)
pagos_dm = pd.read_parquet(pagos_dm_file)

In [2]:
import pandas as pd

In [8]:
parque_total_valores = pd.read_parquet(r"C:\Users\katherine.Builes\OneDrive - Valor+ SAS\utilidades\omisos\data omisos\output\20250601_parque_total__valores_depurado.parquet")

In [9]:
parque_total_valores.columns

Index(['PLACA', 'ESTADO', 'MUNICIPIO', 'DEPARTAMENTO',
       'INTERLOCUTOR_COMERCIAL', 'ID_USUARIO', 'TIPO_DOCUMENTO', 'VIGENCIA',
       'SUBREGION', 'CLASE', 'FECHA_MATRICULA', 'IMPUESTO', 'SANCIONES',
       'INTERESES', 'IMPUESTO_CALCULADO', 'SANCION_CALCULADA',
       'INTERESES_CALCULADOS', 'PLACA-VIGENCIA'],
      dtype='object')

In [10]:
parque_total_valores.head()

,PLACA,ESTADO,MUNICIPIO,DEPARTAMENTO,INTERLOCUTOR_COMERCIAL,ID_USUARIO,TIPO_DOCUMENTO,VIGENCIA,SUBREGION,CLASE,FECHA_MATRICULA,IMPUESTO,SANCIONES,INTERESES,IMPUESTO_CALCULADO,SANCION_CALCULADA,INTERESES_CALCULADOS,PLACA-VIGENCIA
148218,ZXZ97,PLACA OMISA,MEDELLIN,ANTIOQUIA,None,98559636,CC,2004,VALLE DEL ABURRA,MOTOCICLETAS,1992-01-01,84000.0,149000.0,258000.0,84000.0,249000.0,454000.0,ZXZ97-2004
148222,ZXZ70,PLACA OMISA,YOLOMBO,ANTIOQUIA,None,71172083,1,2004,NORDESTE,MOTOCICLETAS,1994-01-01,29000.0,0.0,0.0,29000.0,249000.0,158000.0,ZXZ70-2004
148225,ZXZ50,PLACA OMISA,MEDELLIN,ANTIOQUIA,None,8000682800,N,2004,VALLE DEL ABURRA,MOTOCICLETAS,1994-01-01,29000.0,123000.0,54000.0,29000.0,249000.0,157000.0,ZXZ50-2004
148226,ZXZ40,PLACA OMISA,LA CEJA,ANTIOQUIA,None,71629485,C,2004,ORIENTE,MOTOCICLETAS,1994-07-08,29000.0,178000.0,120000.0,29000.0,249000.0,158000.0,ZXZ40-2004
148227,ZXZ23,PLACA OMISA,FREDONIA,ANTIOQUIA,None,71624336,C,2004,SUROESTE,MOTOCICLETAS,1994-01-01,29000.0,119000.0,38400.0,29000.0,249000.0,157000.0,ZXZ23-2004

In [11]:
parque_total_valores.ESTADO.value_counts()

ESTADO
PLACA OMISA              4393872
PERSONA INDETERMINADA     440938
ACUERDO DE PAGO           127924
PAGO DE LA OBLIGACION         16
Name: count, dtype: int64

In [12]:
parque_total_omiso= parque_total_valores[parque_total_valores["ESTADO"]=="PLACA OMISA"]

In [13]:
parque_total_omiso["IMPUESTO"].isnull().sum()

np.int64(818192)

In [14]:
parque_total_omiso.ESTADO.value_counts()

ESTADO
PLACA OMISA    4393872
Name: count, dtype: int64

In [15]:
parque_omiso=parque_total_omiso[parque_total_omiso["VIGENCIA"] != 2025]

In [16]:
parque_omiso["IMPUESTO"].isnull().sum()

np.int64(118048)

In [15]:
parque_omiso.head()

,PLACA,ESTADO,MUNICIPIO,DEPARTAMENTO,INTERLOCUTOR_COMERCIAL,ID_USUARIO,TIPO_DOCUMENTO,VIGENCIA,SUBREGION,CLASE,FECHA_MATRICULA,IMPUESTO,SANCIONES,INTERESES,IMPUESTO_CALCULADO,SANCION_CALCULADA,INTERESES_CALCULADOS,PLACA-VIGENCIA
148218,ZXZ97,PLACA OMISA,MEDELLIN,ANTIOQUIA,None,98559636,CC,2004,VALLE DEL ABURRA,MOTOCICLETAS,1992-01-01,84000.0,149000.0,258000.0,84000.0,249000.0,455000.0,None
148219,ZXZ91,PLACA OMISA,GIRARDOTA,ANTIOQUIA,None,8399587,C,2004,VALLE DEL ABURRA,MOTOCICLETAS,1994-01-01,NaN,NaN,NaN,NaN,NaN,NaN,None
148220,ZXZ83,PLACA OMISA,CALDAS,ANTIOQUIA,None,71215054,1,2004,VALLE DEL ABURRA,MOTOCICLETAS,1994-01-01,NaN,NaN,NaN,NaN,NaN,NaN,None
148221,ZXZ80,PLACA OMISA,MEDELLIN,ANTIOQUIA,None,71603351,1,2004,VALLE DEL ABURRA,MOTOCICLETAS,1994-01-01,NaN,NaN,NaN,NaN,NaN,NaN,None
148222,ZXZ70,PLACA OMISA,YOLOMBO,ANTIOQUIA,None,71172083,1,2004,NORDESTE,MOTOCICLETAS,1994-01-01,29000.0,0.0,0.0,29000.0,249000.0,159000.0,None

In [1]:
from pathlib import Path

In [2]:
home = Path.home()

In [4]:
pagos_dm = pd.read_parquet(f"{home}\\OneDrive - Valor+ SAS\\analitica_impuestos\\depurada\\pagos.parquet")
pagos_dm['PLACA-VIGENCIA'] = pagos_dm['PLACA'] +"-"+ pagos_dm['VIGENCIA_PAGO'].astype(str)

In [16]:
parque_omiso['PLACA-VIGENCIA']=parque_omiso['PLACA-VIGENCIA']+"-"+parque_omiso['PLACA-VIGENCIA']

C:\Users\katherine.Builes\AppData\Local\Temp\ipykernel_24796\1655427330.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  parque_omiso['PLACA-VIGENCIA']=parque_omiso['PLACA-VIGENCIA']+"-"+parque_omiso['PLACA-VIGENCIA']

In [21]:
parque_omiso[parque_omiso['PLACA-VIGENCIA'] =='XIA074-2023']

Empty DataFrame
Columns: [PLACA, ESTADO, MUNICIPIO, DEPARTAMENTO, INTERLOCUTOR_COMERCIAL, ID_USUARIO, TIPO_DOCUMENTO, VIGENCIA, SUBREGION, CLASE, FECHA_MATRICULA, IMPUESTO, SANCIONES, INTERESES, IMPUESTO_CALCULADO, SANCION_CALCULADA, INTERESES_CALCULADOS, PLACA-VIGENCIA]
Index: []

In [17]:
parque_omiso_incluido_2025_validados = parque_omiso[~parque_omiso["PLACA-VIGENCIA"].isin(pagos_dm["PLACA-VIGENCIA"])]

In [22]:
parque_omiso_incluido_2025_validados["IMPUESTO"].isnull().sum()

np.int64(417300)

In [19]:
pagos=pd.read_csv(r"C:\Users\katherine.Builes\OneDrive - Valor+ SAS\laura\Consolidado Pagos 2025.csv",sep=";")

MemoryError: Unable to allocate 65.6 MiB for an array with shape (9, 955727) and data type object

In [ ]:
pagos.columns

Index(['St_', 'Tipo_de_Pago', 'Cod__Banco', 'Inst__Financiera',
       'Cta__Compens_', 'Cta__Bancaria', 'Lotes_de_pagos', 'Doc_Cobro',
       'Fecha_de_pago', 'Con_Clarif_', 'Vigencia', 'Referencia', 'Placa',
       'Avaluo', 'Valor_del_Lote', 'Valor_Pagado', 'DPP', '_DPP', 'Impuesto',
       'Sanciones', 'Intereses', 'Serv_Inform', 'Benef_Sanciones',
       'Benef_Intereses', 'Municipio', 'Direccion', 'Region', 'Int_Comerc',
       'Creado_Por', 'Fch_Creacion', 'Hr_Creacion', 'Modif_Por', 'Fch_Modif',
       'Hr_Modif', 'Doc_Compens', 'Doc_Clarif'],
      dtype='object')

In [ ]:
pagos['PLACA-VIGENCIA']=pagos['Placa']+"-"+pagos['Vigencia'].astype(str)

In [ ]:
parque_omiso_incluido_2025_validados = parque_omiso_incluido_2025_validados[~parque_omiso_incluido_2025_validados["PLACA-VIGENCIA"].isin(pagos["PLACA-VIGENCIA"])]

In [ ]:
parque_omiso_incluido_2025_validados["IMPUESTO"].isnull().sum()

np.int64(417300)

In [ ]:
parque_omiso_incluido_2025_validados[parque_omiso_incluido_2025_validados["IMPUESTO"].isnull()].sample(15)

,PLACA,ESTADO,MUNICIPIO,DEPARTAMENTO,INTERLOCUTOR_COMERCIAL,ID_USUARIO,TIPO_DOCUMENTO,VIGENCIA,SUBREGION,CLASE,FECHA_MATRICULA,IMPUESTO,SANCIONES,INTERESES,IMPUESTO_CALCULADO,SANCION_CALCULADA,INTERESES_CALCULADOS,PLACA-VIGENCIA
1390498,EKO729,PLACA OMISA,EL CARMEN DE VIBORAL,ANTIOQUIA,None,70690087,C,2007,ORIENTE,VEHICULOS,2004-02-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1367280,LLD314,PLACA OMISA,ENVIGADO,ANTIOQUIA,None,32430670,C,2007,VALLE DEL ABURRA,VEHICULOS,1980-02-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155783,MLE589,PLACA OMISA,MEDELLIN,ANTIOQUIA,None,8909201954,2,2004,VALLE DEL ABURRA,VEHICULOS,1991-03-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5289889,ELL535,PLACA OMISA,SIN MUNICIPIO,SIN DEPARTAMENTO,None,None,None,2013,SIN SUBREGION,VEHICULOS,2008-11-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6979532,LEJ851,PLACA OMISA,BOGOTA,CUNDINAMARCA,None,7307702,1,2015,SIN SUBREGION,VEHICULOS,1979-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16444988,PDM87B,PLACA OMISA,MEDELLIN,ANTIOQUIA,None,87510091,C,2023,VALLE DEL ABURRA,MOTOCICLETAS,2008-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3821854,LX2168,PLACA OMISA,SIN MUNICIPIO,SIN DEPARTAMENTO,None,None,None,2011,SIN SUBREGION,VEHICULOS,1975-08-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
707569,MLA988,PLACA OMISA,SIN MUNICIPIO,SIN DEPARTAMENTO,None,None,None,2005,SIN SUBREGION,VEHICULOS,1989-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4487609,RCJ780,PLACA OMISA,BOGOTA,CUNDINAMARCA,None,14315366,C,2012,SIN SUBREGION,VEHICULOS,1979-06-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1575867,FAY408,PLACA OMISA,BOGOTA,CUNDINAMARCA,1002528887,72429154,CC,2007,SIN SUBREGION,VEHICULOS,2004-09-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16904229,LFD667,PLACA OMISA,SIN MUNICIPIO,SIN DEPARTAMENTO,None,None,None,2023,SIN SUBREGION,VEHICULOS,1983-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN
666471,MLG896,PLACA OMISA,CARTAGENA,BOLIVAR,None,8284478,C,2005,SIN SUBREGION,VEHICULOS,1992-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN
714285,KBH833,PLACA OMISA,SIN MUNICIPIO,SIN DEPARTAMENTO,None,None,None,2005,SIN SUBREGION,VEHICULOS,1982-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2589909,PSA038,PLACA OMISA,SIN MUNICIPIO,SIN DEPARTAMENTO,None,None,None,2009,SIN SUBREGION,VEHICULOS,1961-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1569632,LFB110,PLACA OMISA,SIN MUNICIPIO,SIN DEPARTAMENTO,None,None,None,2007,SIN SUBREGION,VEHICULOS,1978-03-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
import pandas as pd

In [3]:
parque = pd.read_parquet(r"C:\Users\Katherine Builes L\OneDrive - Valor+ SAS\utilidades\omisos\data omisos\output\20260805_parque_total.parquet")

In [7]:
parque.columns

Index(['PLACA', 'ESTADO', 'MUNICIPIO', 'DEPARTAMENTO',
       'INTERLOCUTOR_COMERCIAL', 'ID_USUARIO', 'TIPO_DOCUMENTO', 'VIGENCIA',
       'SUBREGION', 'CLASE', 'FECHA_MATRICULA'],
      dtype='object')

In [2]:
import pandas as pd

In [3]:
homo = pd.read_csv(r"C:\Users\Katherine Builes L\OneDrive - Valor+ SAS\solicitudes\cartera_postjulio\homo_2024_2025_new.csv",sep=";")

C:\Users\Katherine Builes L\AppData\Local\Temp\ipykernel_1016\3564545015.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  homo = pd.read_csv(r"C:\Users\Katherine Builes L\OneDrive - Valor+ SAS\solicitudes\cartera_postjulio\homo_2024_2025_new.csv",sep=";")

In [4]:
homo.head()

,PLACA,GRUPO,Estado generalizado,MODELO,CLASE,CILINDRAJE,AVALUO,RANGO AVALUO,TARIFA,RANGO CLASE,VIGENCIA
0,000AAA,M407,LIQUIDA,2012.0,MOTOCARRO,198.0,4320000,[0 - 5.000.000],1.5,MOTOCICLETA,2024
1,000AAC,M356,LIQUIDA,2011.0,MOTOCARRO,181.0,3480000,[0 - 5.000.000],1.5,MOTOCICLETA,2024
2,000AAM,M407,LIQUIDA,2012.0,MOTOCARRO,198.0,4320000,[0 - 5.000.000],1.5,MOTOCICLETA,2024
3,000ABZ,M355,LIQUIDA,2017.0,MOTOCARRO,197.0,5440000,[5.000.001 - 10.000.000],1.5,MOTOCICLETA,2024
4,000ACM,M355,LIQUIDA,2021.0,MOTOCARRO,197.0,8780000,[5.000.001 - 10.000.000],1.5,MOTOCICLETA,2024

In [6]:
homo[homo["PLACA"]=="KBD466"]

,PLACA,GRUPO,Estado generalizado,MODELO,CLASE,CILINDRAJE,AVALUO,RANGO AVALUO,TARIFA,RANGO CLASE,VIGENCIA
782679,KBD466,Q199,LIQUIDA,1956.0,CAMION,2300.0,8340000,[5.000.001 - 10.000.000],1.5,BUSES Y CAMIONES,2024
1816087,KBD466,Q202,NaN,1956.0,CAMION,2300.0,8340000,['5.000.001 - 10.000.000'],1.5,BUSES Y CAMIONES,2025