In [1]:
import pandas as pd

In [3]:
pagos=pd.read_parquet(r"C:\Users\katherine.Builes\OneDrive - Valor+ SAS\laura\Consolidado campañas\pagos_2025.parquet")

In [4]:
pagos.head()

,PLACA,ID,MES,VIGENCIA,IMPUESTO,SANCIONES,INTERESES,SERV_INFORM,ID_MES,PAGO GESTIONADO
0,ESY29A,71688437,4,2008,33000.0,249000.0,146000.0,24600.0,71688437_4,NO
1,ESY29A,71688437,4,2009,30000.0,249000.0,125000.0,24600.0,71688437_4,NO
2,LMJ328,70123085,4,2008,53000.0,249000.0,235000.0,24600.0,70123085_4,SI
3,LMJ328,70123085,4,2009,42000.0,249000.0,175000.0,24600.0,70123085_4,SI
4,LWH953,70384519,4,2008,87000.0,249000.0,385000.0,24600.0,70384519_4,SI

In [5]:
pagos["vigencia-placa"]=pagos["VIGENCIA"]+pagos["PLACA"]

In [6]:
pagos.head()

,PLACA,ID,MES,VIGENCIA,IMPUESTO,SANCIONES,INTERESES,SERV_INFORM,ID_MES,PAGO GESTIONADO,vigencia-placa
0,ESY29A,71688437,4,2008,33000.0,249000.0,146000.0,24600.0,71688437_4,NO,2008ESY29A
1,ESY29A,71688437,4,2009,30000.0,249000.0,125000.0,24600.0,71688437_4,NO,2009ESY29A
2,LMJ328,70123085,4,2008,53000.0,249000.0,235000.0,24600.0,70123085_4,SI,2008LMJ328
3,LMJ328,70123085,4,2009,42000.0,249000.0,175000.0,24600.0,70123085_4,SI,2009LMJ328
4,LWH953,70384519,4,2008,87000.0,249000.0,385000.0,24600.0,70384519_4,SI,2008LWH953

In [7]:
pagos[pagos["vigencia-placa"]=="2016AMK28B"]

Empty DataFrame
Columns: [PLACA, ID, MES, VIGENCIA, IMPUESTO, SANCIONES, INTERESES, SERV_INFORM, ID_MES, PAGO GESTIONADO, vigencia-placa]
Index: []

In [8]:
campañas=pd.read_parquet(r"C:\Users\katherine.Builes\OneDrive - Valor+ SAS\laura\Consolidado campañas\consolidado_campañas_tablero_2025_v2.parquet")

In [9]:
campañas.head()

,ID,CANAL,PLACA,NOMBRE_ARCHIVO,CATEGORIA ESTRATEGIA,VIGENCIA,CATEGORIA VIGENCIAS CAMPAÑA,DATO CONTACTO,MES,ID_MES,ESTADO PAGO,ESTADO LIQUIDACION
0,1033336627,EMAIL,SJZ68A,1. Campaña cierre contable vigencias anteriore...,FECHAS DISMINUCION TEMPORAL SANCION E INTERESE...,2024,VIGENCIAS ANTERIORES,carlosestrada10@copomo.com,1,1033336627_1,SIN PAGO,SIN LIQUIDACION
1,1033336627,EMAIL,SJZ68A,1. Campaña cierre contable vigencias anteriore...,FECHAS DISMINUCION TEMPORAL SANCION E INTERESE...,2024,VIGENCIAS ANTERIORES,jamerzelagon@gmail.com,1,1033336627_1,SIN PAGO,SIN LIQUIDACION
2,32110961,EMAIL,SJZ70A,1. Campaña cierre contable vigencias anteriore...,FECHAS DISMINUCION TEMPORAL SANCION E INTERESE...,2024,VIGENCIAS ANTERIORES,mo0785782@gmail.com,1,32110961_1,SIN PAGO,SIN LIQUIDACION
3,21551935,EMAIL,SJZ71A,1. Campaña cierre contable vigencias anteriore...,FECHAS DISMINUCION TEMPORAL SANCION E INTERESE...,2024,VIGENCIAS ANTERIORES,ts3366985@gmail.com,1,21551935_1,SIN PAGO,SIN LIQUIDACION
4,21551935,EMAIL,SJZ71A,1. Campaña cierre contable vigencias anteriore...,FECHAS DISMINUCION TEMPORAL SANCION E INTERESE...,2024,VIGENCIAS ANTERIORES,deisyhenao3107@hotmail.com,1,21551935_1,SIN PAGO,SIN LIQUIDACION

In [10]:
campañas["vigencia-placa"]=campañas["VIGENCIA"]+campañas["PLACA"]

In [11]:
campañas[campañas["vigencia-placa"]=="2016AMK28B"]

,ID,CANAL,PLACA,NOMBRE_ARCHIVO,CATEGORIA ESTRATEGIA,VIGENCIA,CATEGORIA VIGENCIAS CAMPAÑA,DATO CONTACTO,MES,ID_MES,ESTADO PAGO,ESTADO LIQUIDACION,vigencia-placa
2320541,8161408,EMAIL,AMK28B,2.Campaña disminución temporal 2016 email.csv,DISMINUCIÓN TEMPORAL,2016,VIGENCIAS ANTERIORES,alejos157@gmail.com,1,8161408_1,CON PAGO,CON LIQUIDACION,2016AMK28B
10771773,8161408,WHATSAPP,AMK28B,1.Campaña disminución temporal whatsapp.csv,DISMINUCION TEMPORAL,2016,VIGENCIAS ANTERIORES,3218420567,1,8161408_1,CON PAGO,CON LIQUIDACION,2016AMK28B